# Generated by Django 3.2.16 on 2022-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_lead_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.CharField(choices=[('FEATURED', 'Featured'), ('NOT FEATURED', 'Not Featured')], default='NOT FEATURED', max_length=20),
        ),
    ]
