# Generated by Django 3.2.16 on 2022-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_featured',
            field=models.ImageField(default='article-default.jpg', upload_to='article_pics'),
        ),
    ]
